CMD_ALIASES:
  [
    { name: "play", aliases: ["p", "pl"] },
    { name: "help", aliases: ["h", "hlp"] },
    { name: "stop", aliases: ["stp"] },
    { name: "credits", aliases: ["c"] },
    { name: "profile", aliases: ["pf"] },
  ]
BOT:
  ACTIVITYS: { name: "/help", type: "COMPETING" }
  STATUS: "idle"
  TOKEN: "MTA4MTU3NTQ0MjAzODkzMTQ5Ng.GUtD2x.QaTavv9Gk0kkT_85mVQpYQ3n3-xWsGwO5HTK9I"
  PREFIX: "+"
  lavalink:
    {
      host: "node1.kartadharta.xyz",
      password: "kdlavalink",
      secure: true,
      port: 443,
    }
REPLYS:
  videoNOT: "🎥 new video!!! {videoName} ( {videoURL} )"
  en:
    noPerms: "🚫 | You don't have permissions to acess This command."
    langChange: "📜 | The bot language has been changed from `english` to `arabic`"
    noArg: "🚫 | There is a missing entry that you should include next to the command: `{arg}`."
    noArgC: "🚫 | This option have to be one of these: `{c}`."
    doneBAN: "✈ | {userTAG}, got banned , reason: `{reason}`"
    errBAN: "🚫 | I can't ban this member sadly."
    doneKICK: "✈ | {userTAG}, got kicked , reason: `{reason}`"
    errKICK: "🚫 | I can't kick this member sadly."
    unbanDONE: "🛬 | {userTAG}, Has been unbaned."
    unbanNOTfind: "🚫 | I can't find this user in the ban list."
    unbanERR: "🚫 | I can't unban this user for some reasons."
    doneNICK: "📜 | Done change the nickname for `{userUsername}` to `{nickname}`."
    errNICK: "🚫 | I can't change nickname for some reasons."
    doneMUTE: "🔇 | {userTAG} Has been muted for `{time}`."
    errMUTE: "🚫 | I can't mute this user for some reasons."
    doneUNMUTE: "🔊 | {userTAG} Has unmuted."
    errUNMUTE: "🚫 | I can't unmute this user for some reasons."
    cantROLE: "🚫 | I can't find this role sadly."
    cantROLE2: "🚫 | I can't find this user sadly."
    undefinedAction: "🚫 | Undefined action [add, remove]"
    muteHIMself: "🚫 | You can't mute your self."
    doneROLING: "📜 | Action has been taken `{action}` with object `{who}` on the role `{role}`"
    doneLOCK: "🔒 | Channel has been locked."
    doneUNLOCK: "🔓 | Channel has been unlocked"
    slowDONE: "🐌 | Slow mode time has  changed."
    colorDOne: "🎨 | The role color has changed."
    mc1: ":no_entry_sign: You must join a voice channel to use that!"
    mc2: ":no_entry_sign: You must be listening in ${botVoiceChannel.name} to use that!"
    mc3: ":notes: Resumed {songName}"
    mc4: ":notes: {songName} Added to ProQueue (`{time}`)!"
    mc5: ":no_entry_sign: There must be music playing to use that!"
    mc6: ":bulb: The player is already paused! Use `/resume to` unpause!"
    mc7: ":notes: Paused {songName} Type `/play` to unpause!"
    mc8: ":bulb: The player is not paused! Use `/pause` to pause!"
    mc9: ":notes: Resumed {songName}"
    mc10: ":x: bot is not currently playing."
    mc11: ":notes: Repeat Mode: {mode}"
    mc12: ":no_entry_sign: Please include a query."
    mc13: ":notes: The player has stopped and the queue has been cleared."
    mc14: ":notes: Skipped {songName} - <@!{reqID}>"
    mc15: ":no_entry_sign: Volume must be a valid integer between 0 and 150!"
    mc16: ":loud_sound: Volume changed from `{songVol}` to `{vol}`"
    doneSHOW: "👁 | Channel on view."
    doneHIDE: "👁 | Channel on hiden."
    FILES_ONLY: "🖼 | this channel has been set as files-only"
    FILES_ONLY_DEL: "🖼 | files-only channel has been deleted"
    emojiADD: "🎃 | Done Added {emoji} Emoji In Your Server"
    preCOLORS: "🕑 | Preparing your server color rules ..."
    doneCOLORS: "✅ | Your colors is ready"
    noCOLOR: "🚫 | There is no color with this number."
    doCOLOR: "🎨 | your color has changed."
    doneDisableLS: "💹 | Leveling system is `{status}`."
    LSCupdated: "💹 | Levling channel has updated."
    LSMupdate: "💹 | Levling message has updated."
    notAlevel: "🚫 | The level must be a number."
    rewardIsHere: "🚫 | This reward is already in the database."
    updateRewards: "💹 | Rewards list data has been updated."
    reLS: "💹 | Server members points has been reseted."
    cmdOptionsNana: "🚫 | All command options have to be numbers."
    clearDone: "🧹 | Deleting Messages is on Progress..."
    doneMakedARes: "🤖 | Done set the auto responce."
    doneDeleteARes: "🤖 | Done delete the auto responce."
    doneUpdateARole: "🤖 | Done update the auto role for members."
    doneDeleteARole: "🤖 | Done delete the auto role."
    doneLINE: "🤖 | Done set line in this channel."
    deleLINE: "🤖 | Done delete the line in this channel."
    cantBanurSelf: "🚫 | You can't ban your self."
    cantKickurSelf: "🚫 | You can't kick your self."
    urcredits: ":bank: | {user.username}, your account balance is `${credits}`"
    transFrWOOO: "🚫 | {author.username}, transfer for who??"
    urCisGant: "🚫 | {author.username}, You don't have any credits in your account!"
    cmjdiehu: "🚫 | {author.username}, Your balance is not enough for that!"
    onlyNUMMMS: "🚫 | {author.username}, Only numbers!"
    nowooordsa: "🚫 | {user.username}, Type a Amount `Not Negative`"
    doneTrans: ":moneybag: | {author.username}, has transferred `${amount}` to {user}"
    prefixChange: "🔧 | Bot prefix has been changed to `{pref}`"
    coolDown: "⏰ | You are in cooldown {time}"
    doneTempChannelCreated: "🔊 | Temp channels has been created."
    marwaaaaaaaaaaaaanPabloooooooooooo: "🕳 | Mention welcomer has enabled."

    ban_kickREASONS:
      [
        { label: "Spam", value: "Spam" },
        { label: "Swaering", value: "Swaering" },
        { label: "Scam", value: "Scam" },
        { label: "Hacking", value: "Hacking" },
        { label: "Bitching", value: "Bitching" },
      ]
  ar:
    noPerms: "🚫 | ليس لديك صلحيات لأستخدام هذا الأمر."
    langChange: "📜 | تم تغير لغة البوت من `عربي` الى `انجليزي`"
    noArg: "🚫 | يوجد إدخال مفقود يجب عليك تضمينه بجوار الأمر: `{arg}`."
    doneBAN: "✈ | {userTAG}, قد تم حظرة , السبب: `{reason}`"
    errBAN: "🚫 | لا يمكنني حظر هذا الشخص لبعض الأسباب.."
    doneKICK: "✈ | {userTAG}, قد تم طردة , السبب: `{reason}`"
    errKICK: "🚫 | لا يمكنني طرد هذا الشخص لبعض الأسباب."
    unbanDONE: "🛬 | {userTAG}, قد حزف من قائمة المحظورين"
    unbanNOTfind: "🚫 | انا لا اجد هذا الشخص على قائمة الحظورين"
    unbanERR: "🚫 | لا يمكنني فك الحظر عن هذا الشخص لبعض الأسباب."
    doneNICK: "📜 | تم تغير اسم `{userUsername}` ل `{nickname}`"
    errNICK: "🚫 | لا يمكنني تغير اسم هذا الشخص لبعض الأسباب."
    doneMUTE: "🔇 | {userTAG} تم اسكاته لمدة `{time}`."
    errMUTE: "🚫 | لا يمكنني اسكات هذا الشخص لبعض الأسباب.."
    doneUNMUTE: "🔊 | {userTAG} تم فك اسكاته."
    errUNMUTE: "🚫 | لا يمكنني فك اسكات هذا الشخص لبعض الأسباب.."
    cantROLE: "🚫 | لا يمكنني العثور على هذه الرتبة اللعينه."
    cantROLE2: "🚫 | لا يمكنني العثور على هذا الشخص اللعين."
    doneROLING: "📜 | تم اتخاز اجراء `{action}` مع العنصر `{who}` على الرتبة `{role}`"
    undefinedAction: "🚫 | الأجراء غير معروف [add, remove]"
    doneLOCK: "🔒 | تم اغلاق الغرفة."
    doneUNLOCK: "🔓 | تم فتح الغرفة."
    slowDONE: "🐌 | وضع الأبطاء تم تغيره."
    colorDOne: "🎨 | تم تغير لون الرتبة."
    mc1: ":no_entry_sign: يجب ان تكون في غرفة صوتية لأستخدام هذا الأمر!"
    mc2: ":no_entry_sign: عليك ان تنضم لـ ${botVoiceChannel.name} لأستخدام هذا الأمر!"
    mc3: ":notes: مستأنف {songName}"
    mc4: ":notes: {songName} تمت إضافته إلى Queue (`{time}`)!"
    mc5: ":no_entry_sign: يجب أن يكون هناك تشغيل الموسيقى لاستخدام هذا الأمر!"
    mc6: ":bulb: مشغل الأغاني تم ايقافه مسبقاَ! استعمل `/resume to` لألغاء ايقافه!"
    mc7: ":notes: متوقف مؤقتًا {songName} استعمل `/play` للأستكمال!"
    mc8: ":bulb: مشغل الأغاني يعمل بالفعل! استعمل `/pause` للتوقف!"
    mc9: ":notes: مستأنف {songName}"
    mc10: ":x: النظام لا يلعب اي اغنيه."
    mc11: ":notes: وضع التكرار: {mode}"
    mc12: ":no_entry_sign: يؤجى ارفاق كلمة للبحث."
    mc13: ":notes: قد توقف نظام تشغيل الأغاني و حزف طابور الأغاني."
    mc14: ":notes: تخطي {songName} - <@!{reqID}>"
    mc15: ":no_entry_sign: يجب أن يكون مستوى الصوت عددًا صحيحًا يتراوح بين 0 و 150!"
    mc16: ":loud_sound: تم تغيير مستوى صوت الموسيقى من `{songVol}` لـ `{vol}`"
    doneSHOW: "👁 | القناة معروضة."
    doneHIDE: "👁 | القناه مخفية."
    FILES_ONLY: "🖼 | هذه القناة عينة للملفات و الصور فقط"
    FILES_ONLY_DEL: "🖼 | غرفة الملفات قد حزفت"
    emojiADD: "🎃 | تم اضافة الأيموجي {emoji} للخادم"
    preCOLORS: "🕑 | جاري تجهيز الوان خادمك ..."
    doneCOLORS: "✅ | الوانك جاهزه"
    noCOLOR: "🚫 | لا يوجد لون بهاذا الرقم."
    doCOLOR: "🎨 | تم تغير لونك."
    doneDisableLS: "💹 | نظام المستوى `{status}`."
    LSCupdated: "💹 | قناة اشعارات المستوى. قد تم تغيرها."
    LSMupdate: "💹 | رسالة اشعارات المستوى. قد تغيرت."
    notAlevel: "🚫 | المستوى يجب ان يكون رقم صحيح."
    rewardIsHere: "🚫 | هذه الجائزه موجوده بلفعل في قاعدة البانات."
    updateRewards: "💹 | قائمة جوائز المستوى. قد عدلت."
    reLS: "💹 | كل نقاط المستوى قد تم تصفيرها."
    cmdOptionsNana: "🚫 | كل اختيارات الأمر يجب ان تكون ارقام صحيحه."
    clearDone: "🧹 | حزف الرسائل قايد التقدم..."
    doneMakedARes: "🤖 | تم وضع الرد التلقائي."
    doneDeleteARes: "🤖 | تم حزف الرد التلقائي."
    doneUpdateARole: "🤖 | تم تعديل الرتبة التلقائيه للأعضاء."
    doneDeleteARole: "🤖 | تم حزف الرتبة التلقائيه للأعضاء."
    doneLINE: "🤖 | تم وضع الخط في هذه القناة"
    deleLINE: "🤖 | تم حزف الخط من القناه"
    cantBanurSelf: "🚫 | لا يمكنك حظر نفسك."
    cantKickurSelf: "🚫 | لا يمكنك طرد نفسك."
    urcredits: ":bank: | {user.username}, قيمة حسابك الحالية هي `${credits}`"
    transFrWOOO: "🚫 | {author.username}, لمن تريد التحويل??"
    urCisGant: "🚫 | {author.username}, أنت عل جنظ من الأخر!"
    cmjdiehu: "🚫 | {author.username}, كحيان معكش فلوس!"
    onlyNUMMMS: "🚫 | {author.username}, الأرقام فقط!"
    nowooordsa: "🚫 | {user.username}, الأرقام السالبه غير محققه"
    doneTrans: ":moneybag: | {author.username}, تم تحويل مبلغ بقيمة `${amount}` لـ {user}"
    prefixChange: "🔧 | تم تغير بادئة البوت لـ `{pref}`"
    coolDown: "⏰ | انت تحت تأثير الأبطاء {time}"
    doneTempChannelCreated: "🔊 | تم أنشاء الغرف المؤقتة."
    marwaaaaaaaaaaaaanPabloooooooooooo: "🕳 | تم تفعلي وضع المنشن الترحيبي."
    ban_kickREASONS:
      [
        { label: "سبام", value: "سبام" },
        { label: " سب", value: "سب" },
        { label: "احتيال", value: "احتيال" },
        { label: "محاولة اختراق", value: "محاولة اختراق" },
        { label: "ترموته", value: "ترموته" },
      ]
